version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: tatilsiz-mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: trivagoDB
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      # Bu port, host makinenizden (örneğin test için) Kafka'ya erişmek için kullanılır.
      - "29092:29092"
      # Bu port, aynı docker network'ündeki diğer servislerin (backend gibi) erişimi içindir.
      # Host'a publish etmeye gerek yok ama görsel olarak kalabilir.
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA'YA ERİŞİM ADRESLERİNİ TANIMLIYORUZ
      # 1. PLAINTEXT://kafka:9092 -> Docker içindeki 'backend' gibi diğer servisler bu adresi kullanacak.
      # 2. OUTSIDE://localhost:29092 -> Bilgisayarınızdan (host) Kafka'ya bağlanmak için bu adresi kullanacaksınız.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:29092
      # HATANIZI GİDEREN EN ÖNEMLİ AYAR: Her listener'a hangi güvenlik protokolünü kullanacağını söylüyoruz.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # Tek node'lu bir Kafka kurduğumuz için bu ayar zorunludur.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  backend:
    build: ./backend
    container_name: tatilsiz-backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/trivagoDB
      # Bu ayar DOĞRU. Backend, Kafka'ya docker network'ü üzerinden bu adresle ulaşacak.
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

volumes:
  mongodb_data: