name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Reposityoyu çek
        uses: actions/checkout@v3

      - name:  Docker kurulu mu kontrol et
        run: docker --version

      - name:  Docker imajı oluştur
        run: docker build -t backend-ci ./backend

      - name:  Konteyneri çalıştır 
        run: docker run -d -p 5000:5000 --name backend-container backend-ci

      - name:  Uygulama çalışıyor mu kontrol et 
        run: |
          sleep 5
          curl --fail http://localhost:5000 || exit 1
